format_version: 3
pipelines:
  greeting-pipeline:
    lock_behavior: lockOnFailure
    group: Project
    materials:
      repo: 
        git: https://github.com/devops-at06/CG_greeting-.git
        branch: master
    stages:
      - Build:
          jobs:
            Building:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - "clean"
                      - "assemble"
              artifacts:
                - build:
                    source: build/libs/*.jar
                    destination: build
      - Test:
          jobs:
            Publishing:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - "clean"
                      - test
                      - jacocoTestReport
                - exec:
                    command: ./gradlew
                    arguments:
                      - check
              artifacts:
                - build:
                    source: build/reports/tests/test/*
                    destination: html_report
                - test:
                    source: build/test-results/test/*xml
                    destination: xml
                - build:
                    source: build/jacoco/**/*
                    destination: jacoco
                - build:
                     source: build/reports/checkstyle/*
                     destination: checkstyle
                - build:
                     source: build/reports/findbugs/*
                     destination: findbugs
                - build:
                     source: build/reports/pmd/*
                     destination: pmd
              tabs:
                Junit_Test: html/index.html
                Xml_Test_Result: xml/TEST-greeting.AppTest.xml
                Test_Summary: html_report/index.html
                checkstyle: checkstyle/main.html
                findbugs: findbugs/main.html
                pmd: pmd/main.html
      - CodeQuality:
          jobs:
            CodeQuality:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - sonarqube
                      - -Dsonar.organization=chritian92-github
                      - -Dsonar.host.url=https://sonarcloud.io
                      - -Dsonar.login=9e466878cd5882f00bb4127599e7623efa322e91
      - Publish:
          jobs:
            pucblishArtifact:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - "uploadArchives"
              artifacts:
                - build:
                    source: repos/*.jar
                    destination: war
